# Generated by Django 5.2.7 on 2025-12-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_categorie', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(null=True)),
            ],
        ),
    ]
